### ISSUE TITLE
The servers are down?

### ISSUE THREAD

**Issue by artemskikh** [prasmussen/glot#11]
Hi! 
I'm using your API and I find it to be very good. Thank you for the awesome API! :)
But I'm having issues these last 2 days (smth around that). Are the servers down?

Running the Hello World example here: https://glot.io/new/c 
results in "Internal Server Error"

**Comment by prasmussen** [comment]
Thanks for letting me know – it was a server problem indeed. I have monitoring for this situation but I had configured the notification settings wrong.

**Comment by artemskikh** [comment]
Thank you for resolving it so quickly 👍
