### ISSUE TITLE
The Perl 6 container looks like it has an old version

### ISSUE THREAD

**Issue by briandfoy** [prasmussen/glot#17]
Is there something that needs to be refreshed? I'm still not quite sure how all the pieces fit together.

* got.io's Perl 6 appears to be running an old version from January (2017.01).

    say $*VM;  # moar (2017.01) on glot.io

* [glot-containers/perl6/latest/Dockerfile](https://github.com/prasmussen/glot-containers/blob/master/perl6/latest/Dockerfile) pulls from [rakudo-star:lastest](https://hub.docker.com/_/rakudo-star/). When I use that Docker file I get Rakudo Star 2107.10 (from October).

**Comment by zoffixznet** [comment]
*bump*

It's been updated since OP was created and now runs 2017.10, which by now is outdated again. Is there a way to automate the process so that latest compiler release is used? Perhaps, with some prodding of some resource by the release manager (cc @AlexDaniel)

**Comment by prasmussen** [comment]
Thanks for reminding me. All images have been updated today.
I am working on automating the process, though at a slow pace :)
