### ISSUE TITLE
Not really an issue but still fun

### ISSUE THREAD

**Issue by mluczak** [prasmussen/glot#18]
<img width="1209" alt="screen shot 2018-01-05 at 16 21 39" src="https://user-images.githubusercontent.com/3452983/34615319-c87b26e4-f234-11e7-855b-060f58fc6b6f.png">

**Comment by prasmussen** [comment]
Kernel upgraded.
```
[    0.000000] Kernel/User page tables isolation: enabled
```
I guess that solves it.
